"""

Revision ID: 0a74365fc30b
Revises: 850bd77a99c0
Create Date: 2026-04-05 01:35:09.954402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a74365fc30b'
down_revision: Union[str, None] = '850bd77a99c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('github_configs')
    op.drop_table('extension_configs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extension_configs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token_encrypted', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('extension_configs_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('extension_configs_pkey')),
    sa.UniqueConstraint('project_id', name=op.f('extension_configs_project_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('github_configs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('github_token_encrypted', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('webhook_secret', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('signing_secret', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('github_configs_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('github_configs_pkey')),
    sa.UniqueConstraint('project_id', name=op.f('github_configs_project_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
