"""

Revision ID: 0c52dcd620ef
Revises: 0004
Create Date: 2026-04-04 14:46:09.120947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c52dcd620ef'
down_revision: Union[str, None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jira_issue_links_issue_key'), table_name='jira_issue_links')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_jira_issue_links_issue_key'), 'jira_issue_links', ['issue_key'], unique=False)
    # ### end Alembic commands ###
